resource_types:
  - name: setup-runtime-resource
    type: registry-image
    # Seee: https://github.com/concourse/concourse/pull/9017
    privileged: true
    source:
      repository: registry:5000/setup-runtime-resource
      tag: latest
      insecure: true
  - name: mock-via-params
    type: mock
    source:
      initial_version: some-version
    params: { mirror_self_via_params: true }

resources:
  - name: some-resource
    type: mock-via-params
    source:
      initial_version: some-version

  - name: setup-runtime
    type: setup-runtime-resource
    icon: account-hard-hat
    source:
      hook: |
        curl -fSL https://github.com/hairyhenderson/gomplate/releases/download/v4.3.3/gomplate_linux-arm64 -o /usr/local/bin/gomplate
        chmod +x /usr/local/bin/gomplate
      dependencies:
        - curl
      verbose: true
      java:
        version: 21
      telemetry:
        disable: true

jobs:
  - name: test-setup-runtime
    plan:
      - in_parallel:
          - get: setup-runtime
          - get: some-resource
      - task: test-image
        image: setup-runtime
        privileged: true
        config:
          platform: linux
          caches:
            - path: /cache
          inputs:
            - name: setup-runtime
            - name: some-resource
          run:
            path: bash
            args:
              - -ec
              - |  
                gomplate --version

