resource_types:
- name: setup-runtime-resource
  type: registry-image
  # https://github.com/concourse/concourse/pull/9017
  privileged: true
  source:
    repository: registry:5000/setup-runtime-resource
    tag: latest
    insecure: true

resources:
- name: setup-runtime
  type: setup-runtime-resource
  icon: account-hard-hat
  source:
    hook: |
      curl -fSL https://github.com/hairyhenderson/gomplate/releases/download/v4.3.3/gomplate_linux-arm64 -o /usr/local/bin/gomplate
      chmod +x /usr/local/bin/gomplate
    dependencies:
      - wget
      - git
      - curl
    java:
      version: 21
      extra_versions:
        - 25-graalce
    nodejs:
      version: lts
      yarn:
        version: 4.10.2
      pnpm:
        version: 10.17.1
    python:
      version: 3.11
    gradle:
      version: 9.0.0
    maven:
      version: 3.9.9
    testcontainers:
      enabled: true
    telemetry:
      disable: true
    security:
      mode: strictest
      # mode: disabled # not recommended
      # mode: recommended # default (scans rootfs only in get step as a balance between security and performance)
    verbose: true

jobs:
- name: test-setup-runtime
  plan:
  - get: setup-runtime

  - task: test-image
    image: setup-runtime
    privileged: true
    config:
      ((TASK_CONFIG))
