resource_types:
  - name: setup-runtime-resource
    type: registry-image
    source:
      repository: registry:5000/setup-runtime-resource
      tag: latest
      insecure: true
  - name: mock-via-params
    type: mock
    source:
      initial_version: some-version
    params: { mirror_self_via_params: true }

resources:
  - name: some-resource
    type: mock-via-params
    source:
      initial_version: some-version

  - name: setup-runtime
    type: setup-runtime-resource
    icon: account-hard-hat
    source:
      verbose: true
      nodejs:
        version: lts
        yarn:
          version: 4.10.2
        pnpm:
          version: 10.17.1
jobs:
  - name: test-setup-runtime
    plan:
      - in_parallel:
          - get: setup-runtime
          - get: some-resource
      - task: test-image
        privileged: true
        image: setup-runtime
        config:
          platform: linux
          caches:
            - path: /cache
          inputs:
            - name: setup-runtime
            - name: some-resource
          run:
            path: bash
            args:
              - -ec
              - |
                node --version
                yarn --version
                pnpm --version
