resource_types:
- name: setup-runtime-resource
  type: registry-image
  # Running with privileged is not required and is not recommended for production use.
  privileged: true
  source:
    repository: registry:5000/setup-runtime-resource
    tag: ((setup-runtime-resource-tag))
    insecure: true

resources:
- name: setup-runtime
  type: setup-runtime-resource
  icon: account-hard-hat

  source:
    ((SETUP_RUNTIME_SOURCE))

jobs:
- name: test-setup-runtime
  serial: true
  plan:
  - get: setup-runtime

  - task: test-image
    image: setup-runtime
    privileged: true
    config:
      ((TASK_CONFIG))
