resource_types:
- name: setup-runtime-resource
  type: registry-image
  # Running with privileged is not required and is not recommended for production use.
  privileged: true
  source:
    repository: registry:5000/setup-runtime-resource
    tag: ((setup-runtime-resource-tag))
    insecure: true

resources:
- name: setup-runtime
  type: setup-runtime-resource
  icon: account-hard-hat
  source:
    sdkman:
      enabled: true
    nvm:
      enabled: true
    pyenv:
      enabled: true
    telemetry:
      disable: true
    verbose: true

jobs:
- name: test-setup-runtime
  plan:
  - get: setup-runtime

  - task: test-image
    image: setup-runtime
    privileged: true
    config:
      platform: linux

      caches:
        - path: cache
      run:
        path: bash
        args:
          - -ec
          - |
            assert_contains() {
              local needle="$1"
              local input
            
              input="$(cat)"
            
              if [[ "$input" != *"$needle"* ]]; then
                echo "Expected '$needle' to be in '$input'"
                exit 1
              fi
            }
            
            echo "v25.2.1" > .nvmrc
            echo "java=21.0.4-tem" > .sdkmanrc
            
            nvm install
            sdk env install
            
            node --version | assert_contains "25.2.1"
            
            # The source ~/.bashrc is rerequired to set the new candidate in the path variable.
            source ~/.bashrc
            java --version | assert_contains "openjdk 21.0.4"
            java --version | assert_contains "OpenJDK Runtime Environment Temurin-21.0.4"

            mkdir -p subdir
            echo "v25.2.0" > subdir/.nvmrc
            echo "java=21.0.3-tem" > subdir/.sdkmanrc

            cd subdir
            nvm install
            sdk env install
            
            node --version | assert_contains "25.2.0"
            java --version | assert_contains "openjdk 21.0.3"
            java --version | assert_contains "OpenJDK Runtime Environment Temurin-21.0.3"

            cd ..
            
            nvm use
            sdk env install
            
            node --version | assert_contains "25.2.1"
            java --version | assert_contains "openjdk 21.0.4"
            java --version | assert_contains "OpenJDK Runtime Environment Temurin-21.0.4"
        
            echo "3.12.2" > .python-version
            pyenv install --skip-existing
            pyenv local
            python --version | assert_contains "Python 3.12.2"
