resource_types:
- name: setup-runtime-resource
  type: registry-image
  # https://github.com/concourse/concourse/pull/9017
  privileged: true
  source:
    repository: registry:5000/setup-runtime-resource
    tag: latest
    insecure: true

resources:
- name: setup-runtime
  type: setup-runtime-resource
  icon: account-hard-hat
  source:
    ((SETUP_RUNTIME_SOURCE))

jobs:
- name: test-setup-runtime
  plan:
  - get: setup-runtime

  - task: test-image
    image: setup-runtime
    privileged: true
    config:
      ((TASK_CONFIG))
