resource_types:
  - name: setup-runtime-resource
    type: registry-image
    source:
      repository: registry:5000/setup-runtime-resource
      tag: latest
      insecure: true
  - name: mock-via-params
    type: mock
    source:
      initial_version: some-version
    params: { mirror_self_via_params: true }

resources:
  - name: some-resource
    type: mock-via-params
    source:
      initial_version: some-version

  - name: setup-runtime
    type: setup-runtime-resource
    icon: account-hard-hat
    source:
      pyenv:
        enabled: true
      verbose: true

jobs:
  - name: test-setup-runtime
    plan:
      - in_parallel:
          - get: setup-runtime
          - get: some-resource
      - task: test-image
        privileged: true
        image: setup-runtime
        params:
          DEBUG: true
          MAX_CACHE_SIZE_MB: 1024
        config:
          platform: linux
          caches:
            - path: cache
          inputs:
            - name: setup-runtime
            - name: some-resource
          run:
            path: bash
            args:
              - -ec
              - |
                echo "3.12.2" > .python-version
                pyenv install --skip-existing
                pyenv local
                python --version
