#!/bin/bash
set -eo pipefail

payload=$(jq -c .)

version=$(echo "$payload" | jq -r '.version // empty')

if [[ -z "$version" || "$version" == "null" ]]; then
  version="noop"
fi

# Return the version in Concourse's expected format
jq -n --arg ref "$version" '{"version": {"ref": $ref}}'
